### ISSUE TITLE
feature negotiate while using virtio_mmio

### ISSUE THREAD

**Issue by yishangzhang** [oldawei/show_me_the_code#1]
Hello, and thank you for your course! I'm learning with the code in code/s008/virtio-mmio.c, specifically the virtio_mmio_set_guest_features function. Here's the relevant section of the code: [code here](https://github.com/oldawei/show_me_the_code/blob/main/code/s008/source/driver/virtio/virtio-mmio.c#L63-L75),

```
void virtio_mmio_set_guest_features(u64 features)
{
    u32 f0 = features & 0xFFFFFFFF;
    u32 f1 = (features >> 32) & 0xFFFFFFFF;

    VTMO_REG(VIRTIO_MMIO_HOST_FEATURES_SEL) = 0;
    dsb();
    VTMO_REG(VIRTIO_MMIO_GUEST_FEATURES) = f0;

    VTMO_REG(VIRTIO_MMIO_HOST_FEATURES_SEL) = 1;
    dsb();
    VTMO_REG(VIRTIO_MMIO_GUEST_FEATURES) = f1;
}
```
I suspect there might be a need to use the VIRTIO_MMIO_GUEST_FEATURES_SEL register instead of VIRTIO_MMIO_HOST_FEATURES_SEL, but I haven't found any functional errors in s009. When I tried to read the VIRTIO_MMIO_GUEST_FEATURES after setting it, the value was 0. The spec doesn't seem to clarify whether VIRTIO_MMIO_GUEST_FEATURES is readable or not. Additionally, setting it to zero in virtio_mmio_set_guest_features didn't affect the rng-device's functionality. Could you provide any insights on how to verify whether the driver registers have been correctly set? Thank you!

**Comment by wusskk** [comment]
- **我最近也在学习这个代码，我查看了virtio-v1.2-csd01.pdf规范文档，修改DeviceFeatures，确实需要修改DeviceFeaturesSel寄存器。**

![屏幕截图 2024-03-08 103644](https://github.com/oldawei/show_me_the_code/assets/78784599/05a77acb-913f-4364-b572-ee3dbf25bdd8)


- **我尝试打印了代码修改features时寄存器存储的值的变化，确实没有发生改变。**

![屏幕截图 2024-03-06 224910](https://github.com/oldawei/show_me_the_code/assets/78784599/d04ba26d-b42c-4ca4-a09b-6bd198805e4e)
![屏幕截图 2024-03-06 224919](https://github.com/oldawei/show_me_the_code/assets/78784599/9c02a218-3b2b-481b-a35a-a98b02d1cd01)


- **后来我在规范中查到，无法从只写寄存器中读取数据，这应该就是读取始终为0的原因。**

![屏幕截图 2024-03-08 103425](https://github.com/oldawei/show_me_the_code/assets/78784599/53c5b579-f5ee-469b-b472-1b1fbb27d794)

![屏幕截图 2024-03-08 103441](https://github.com/oldawei/show_me_the_code/assets/78784599/93ce6778-4b7d-4191-b1b0-f72387342be2)


- **此外，在virtio_mmio_set_guest_features中将其设置为零不会影响 rng-device 的功能，应该是因为rng写入的驱动特性位都是在低32位，此时DeviceFeaturesSel因为未被修改，默认为零，恰好能够写入。**
![屏幕截图 2024-03-08 104425](https://github.com/oldawei/show_me_the_code/assets/78784599/005d3410-574c-403d-aa87-1df1acda604f)

**Comment by yishangzhang** [comment]
Thank you very much for your sincere answer!   @wusskk
